const LOAD_CATEGORIES_LOADING = "REDUX_THUNK_LOAD_CATEGORIES_LOADING";
const LOAD_CATEGORIES_SUCCESS = "REDUX_THUNK_LOAD_CATEGORIES_SUCCESS";
const LOAD_CATEGORIES_ERROR = "REDUX_THUNK_LOAD_CATEGORIES_ERROR";
const LOAD_MENU_LOADING = "REDUX_THUNK_LOAD_MENU_LOADING";
const LOAD_MENU_SUCCESS = "REDUX_THUNK_LOAD_MENU_SUCCESS";
const LOAD_MENU_ERROR = "REDUX_THUNK_LOAD_MENU_ERROR";
const LOAD_CURRENCIES_LOADING = "REDUX_THUNK_LOAD_CURRENCIES_LOADING";
const LOAD_CURRENCIES_SUCCESS = "REDUX_THUNK_LOAD_CURRENCIES_SUCCESS";
const LOAD_CURRENCIES_ERROR = "REDUX_THUNK_LOAD_CURRENCIES_ERROR";
const LOAD_PRODUCT_LOADING = "REDUX_THUNK_LOAD_PRODUCT_LOADING";
const LOAD_PRODUCT_SUCCESS = "REDUX_THUNK_LOAD_PRODUCT_SUCCESS";
const LOAD_PRODUCT_ERROR = "REDUX_THUNK_LOAD_PRODUCT_ERROR";
const LOAD_CART_ELEMENT_LOADING = "REDUX_THUNK_LOAD_CART_ELEMENT_LOADING";
const LOAD_CART_ELEMENT_SUCCESS = "REDUX_THUNK_LOAD_CART_ELEMENT_SUCCESS";
const LOAD_CART_ELEMENT_ERROR = "REDUX_THUNK_LOAD_CART_ELEMENT_ERROR";
const SET_CURRENCY = "REDUX_SET_CURRENCY";
const SET_CATEGORY = "REDUX_SET_CATEGORY";
const SET_SELECTED_PRODUCT_ID = "REDUX_SET_SELECTED_PRODUCT_ID";
const WAIT_FOR_CART = "REDUX_WAIT_FOR_CART";
const ADD_TO_CART = "REDUX_ADD_TO_CART";
const CALC_TOTAL_PRICE = "REDUX_CALC_TOTAL_PRICE";

export {
    LOAD_CATEGORIES_LOADING,
    LOAD_CATEGORIES_SUCCESS,
    LOAD_CATEGORIES_ERROR,
    LOAD_MENU_LOADING,
    LOAD_MENU_SUCCESS,
    LOAD_MENU_ERROR,
    LOAD_CURRENCIES_LOADING,
    LOAD_CURRENCIES_SUCCESS,
    LOAD_CURRENCIES_ERROR,
    LOAD_PRODUCT_LOADING,
    LOAD_PRODUCT_SUCCESS,
    LOAD_PRODUCT_ERROR,
    LOAD_CART_ELEMENT_LOADING,
    LOAD_CART_ELEMENT_SUCCESS,
    LOAD_CART_ELEMENT_ERROR,
    SET_CURRENCY,
    SET_CATEGORY,
    SET_SELECTED_PRODUCT_ID,
    WAIT_FOR_CART,
    ADD_TO_CART,
    CALC_TOTAL_PRICE,
};
